export const hemoObjOne = {
  id: "about",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transactions with zero fees",
  description: "Get access to your exclusive",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "Car",
  dark: true,
  dark2: true,
  primary: true,
  darkText: false,
};

export const hemoObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Unlimited Access",
  headline: "Unlimited Transactions with zero fees",
  description: "Description Get access to your exclusive",
  buttonLabel: "Learn more",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "Car 2",
  dark: false,
  dark2: false,
  primary: false,
  darkText: true,
};

export const hemoObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Join to the team",
  headline: "Creating an account is exttremely easy",
  description: "Get access to your exclusive",
  buttonLabel: "Start Now",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "Car 3",
  dark: false,
  dark2: false,
  primary: false,
  darkText: true,
};
